import './globals.css'
import type { Metadata } from 'next'
import { League_Spartan } from 'next/font/google'

const league = League_Spartan({ weight: ['500', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${league.className} flex flex-col items-center bg-rear`}
      >
        {children}
      </body>
    </html>
  )
}
